// bind.cpp — AUTOGENERATED

// AUTOGENERATED — DO NOT EDIT"
#include <unordered_map>
#include <string>
#include <array>
#include <sqrat.h>
#include "squirrel.h"

#include "bind.h"
#include "treerat.h"
#include "bind_log.h"
#include "entity.h"
#include "map.h"
#include "methods.h"
#include "statedata.h"
#include "states.h"
using Binder = std::function<void(Sqrat::Table &)>;
using BinderMap = std::unordered_map<std::string, Binder>;


void registerBinding(CTreeRat & rat)
{
    HSQUIRRELVM vm = rat.vm();
    BinderMap registry;



    registry["CStates"] = [](Sqrat::Table &target)
    {
        auto vm = target.GetVM();
        auto cls = Sqrat::Class<CStates>(vm, "CStates")

        // === CStates Class ===
            .Ctor<>()
            .Func("setU", &CStates::setU)
            .Func("setS", &CStates::setS)
            .Func("getU", &CStates::getU)
            .Func("getS", &CStates::getS)
            .Func("hasU", &CStates::hasU)
            .Func("hasS", &CStates::hasS)
            .Func("debug", &CStates::debug)
            .Func("clear", &CStates::clear);
        target.Bind("CStates", cls);
    };

    registry["CMap"] = [](Sqrat::Table &target)
    {
        auto vm = target.GetVM();
        auto cls = Sqrat::Class<CMap>(vm, "CMap")

        // === CMap Class ===
            .Ctor<>()
            .Func("at", &CMap::at)
            .Func("set", &CMap::set)
            .Func("clear", &CMap::clear)
            .Func("len", &CMap::len)
            .Func("hei", &CMap::hei)
            .Func("resize", &CMap::resize)
            .Func("findFirst", &CMap::findFirst)
            .Func("count", &CMap::count)
            .Func("fill", &CMap::fill)
            .Func("getAttr", &CMap::getAttr)
            .Func("setAttr", &CMap::setAttr)
            .Func("size", &CMap::size)
            .Func("lastError", &CMap::lastError)
            .Func("title", &CMap::title)
            .Func("setTitle", &CMap::setTitle)
            .Func("replaceTile", &CMap::replaceTile)
            .Func("statesConst", &CMap::statesConst)
            .StaticFunc("toKey", static_cast<uint16_t (*)(uint8_t, uint8_t)>(&CMap::toKey))
            .StaticFunc("toKeyPos", static_cast<uint16_t (*)(const Pos&)>(&CMap::toKey))
            .StaticFunc("toPos", &CMap::toPos)
            .Func("isValid", &CMap::isValid)
            .Func("shift", &CMap::shift)
            .Func("debug", &CMap::debug);
        target.Bind("CMap", cls);
    };

    registry["Entity"] = [](Sqrat::Table &target)
    {
        auto vm = target.GetVM();
        auto cls = Sqrat::Class<Entity>(vm, "Entity")

        // === Entity Class ===
            .Ctor<>()
            .Func("Move", &Entity::Move)
            .Func("moveDir", &Entity::MoveDir)
            .Func("Damage", &Entity::Damage)
            .Func("GetHealth", &Entity::GetHealth)
            .StaticFunc("getMaxHealth", &Entity::getMaxHealth)
            .ConstVar("name", &Entity::name)
            .Var("X", &Entity::x)
            .Var("y", &Entity::y)
            .Var("health", &Entity::health)
            .Prop("Speed", &Entity::GetSpeed, &Entity::SetSpeed)
            .StaticVar("MAX_HEALTH", &Entity::MAX_HEALTH);
        target.Bind("Entity", cls);
    };
        // === StateValue Enum ===
    registry["StateValue"] = [](Sqrat::Table &target)
    {
        auto vm = target.GetVM();
        auto ct = Sqrat::ConstTable(vm)
            .Const("TIMEOUT", ::StateValue::TIMEOUT)
            .Const("POS_ORIGIN", ::StateValue::POS_ORIGIN)
            .Const("POS_EXIT", ::StateValue::POS_EXIT)
            .Const("MAP_GOAL", ::StateValue::MAP_GOAL)
            .Const("PAR_TIME", ::StateValue::PAR_TIME)
            .Const("YEAR", ::StateValue::YEAR)
            .Const("PRIVATE", ::StateValue::PRIVATE)
            .Const("USERDEF1", ::StateValue::USERDEF1)
            .Const("USERDEF2", ::StateValue::USERDEF2)
            .Const("USERDEF3", ::StateValue::USERDEF3)
            .Const("USERDEF4", ::StateValue::USERDEF4)
            .Const("AUTHOR", ::StateValue::AUTHOR)
            .Const("MSG0", ::StateValue::MSG0)
            .Const("MSG1", ::StateValue::MSG1)
            .Const("MSG2", ::StateValue::MSG2)
            .Const("MSG3", ::StateValue::MSG3)
            .Const("MSG4", ::StateValue::MSG4)
            .Const("MSG5", ::StateValue::MSG5)
            .Const("MSG6", ::StateValue::MSG6)
            .Const("MSG7", ::StateValue::MSG7)
            .Const("MSG8", ::StateValue::MSG8)
            .Const("MSG9", ::StateValue::MSG9)
            .Const("MSGA", ::StateValue::MSGA)
            .Const("MSGB", ::StateValue::MSGB)
            .Const("MSGC", ::StateValue::MSGC)
            .Const("MSGD", ::StateValue::MSGD)
            .Const("MSGE", ::StateValue::MSGE)
            .Const("MSGF", ::StateValue::MSGF);
        target.Bind("StateValue", ct);
    };
        // === Direction Enum ===
    registry["Direction"] = [](Sqrat::Table &target)
    {
        auto vm = target.GetVM();
        auto ct = Sqrat::ConstTable(vm)
            .Const("UP", CMap::Direction::UP)
            .Const("DOWN", CMap::Direction::DOWN)
            .Const("LEFT", CMap::Direction::LEFT)
            .Const("RIGHT", CMap::Direction::RIGHT)
            .Const("MAX", CMap::Direction::MAX)
            .Const("NOT_FOUND", CMap::Direction::NOT_FOUND);
        target.Bind("Direction", ct);
    };

    // === Pos Struct ===
    registry["Pos"] = [](Sqrat::Table &target)
    {
        auto vm = target.GetVM();
        auto cls = Sqrat::Class<Pos>(vm, "Pos")
            .Ctor<int16_t, int16_t>()
            .Var("x", &::Pos::x)
            .Var("y", &::Pos::y);
        target.Bind("Pos", cls);
    };

    Sqrat::Table root = Sqrat::RootTable(rat.vm());

    for (const auto &[name, binder] : registry)
    {
        LOGI("Binding: %s", name.c_str());
        binder(root);
    }

}


void registerGlobal(CTreeRat & rat)
{
    rat.registerFn("printHello", print_hello);
    rat.registerFn("greet", greet);
    rat.registerFn("addNumbers", add_numbers);
    rat.registerFn("LOGI", script_log);
    rat.registerFn("LOGE", script_error);
}

void injectSelectBindings(HSQUIRRELVM vm, Sqrat::Table &sandbox)
{
    const Sqrat::Table root = Sqrat::RootTable(vm);
    const std::array<std::string, 12> whiteList = {
        "Pos",
        "Direction",
        "StateValue",
        "Entity",
        "CMap",
        "CStates",
        "greet",
        "print",
        "LOGI",
        "LOGE",
        "log",
        "error"
    };

    for (const auto& name : whiteList) {
        auto slot = root.GetSlot(name.c_str());
        if (slot.IsNull()) {
            LOGW("injectSelectBindings: '%s' not found in root table", name.c_str());
            continue;
        }
        sandbox.SetValue(name.c_str(), slot);
    }
}
