// bind.h — AUTOGENERATED

#pragma once

// AUTOGENERATED — DO NOT EDIT

#include "squirrel.h"
#include "sqrat.h"

class CTreeRat;

void registerBinding(CTreeRat & rat);
void registerGlobal(CTreeRat & rat);
void injectSelectBindings(HSQUIRRELVM vm, Sqrat::Table &sandbox);