// AUTOGENERATED — DO NOT EDIT

#include "bind.h"
#include "treerat.h"
#include <sqrat.h>
#include "methods.h"
#include "entity.h"

void registerBinding(CTreeRat & rat)
{
    Sqrat::Class<Entity> classEntity(rat.vm(), "Entity");
    classEntity
        .Ctor<>()
        .Func("move", &Entity::Move)
        .Func("Move", &Entity::Move)
        .Func("moveDir", &Entity::MoveDir)
        .Func("Damage", &Entity::Damage)
        .Func("GetHealth", &Entity::GetHealth)
        .StaticFunc("getMaxHealth", &Entity::getMaxHealth)
        .ConstVar("name", &Entity::name)
        .Var("X", &Entity::x)
        .Var("x", &Entity::x)
        .Var("y", &Entity::y)
        .Var("health", &Entity::health)
        .Prop("Speed", &Entity::GetSpeed, &Entity::SetSpeed)
        .StaticVar("MAX_HEALTH", &Entity::MAX_HEALTH);
    Sqrat::RootTable(rat.vm()).Bind("Entity", classEntity);
}

void registerGlobal(CTreeRat & rat)
{
    rat.registerFn("printHello", print_hello);
    rat.registerFn("greet", greet);
    rat.registerFn("addNumbers", add_numbers);
}